### PR TITLE
Login cases. Closes #21. Closes #73.

### LINKED ISSUE #21: Root should redirect to /spaces when logged in
to:
All views

### LINKED ISSUE #73: Do not allow viewing Requests page if not logged in

### PR DESCRIPTION
**Pull request by richo225**
Don't delete the branch after merging. Please :sweat_smile:

### CODE REVIEW

**Comment by arukompas** [comment]
login_spec.rb, line 33. Seems kinda redundant because every single page is going to have content "Spaces" because of the header link. Might wanna replace that with ' expect(current_path).to eq "/spaces" '

**Comment by richo225** [comment]
Good point, didn't see that. I'll change it to the spaces path after the women's cycling final is finished

**Comment by richo225** [comment]
That's the test I tried first but it kept failing because it was staying oin the root. Really strange because it works on rackup test. Might change it to have_content("List a space")

**Comment by richo225** [comment]
It was failing because I was signing up twice. n00b error.

**Comment by arukompas** [comment]
:shipit:

**Pull request merged**
